# Как выжить на титанике

---

Эта тетрадка научит тебя использовать pandas, numpy, строить графики в matplotlib и выживать при кораблекрушении.

Начнём!

##загрузим данные c Pandas

In [1]:
#подключим модуль Pandas.
import pandas, numpy

#считаем данные
data = pandas.DataFrame.from_csv("train(1).csv")
print data

             Survived  Pclass  \
PassengerId
1                   0       3
2                   1       1
3                   1       3
4                   1       1
5                   0       3
6                   0       3
7                   0       1
8                   0       3
9                   1       3
10                  1       2
11                  1       3
12                  1       1
13                  0       3
14                  0       3
15                  0       3
16                  1       2
17                  0       3
18                  1       2
19                  0       3
20                  1       3
21                  0       2
22                  1       2
23                  1       3
24                  1       1
25                  0       3
26                  1       3
27                  0       3
28                  0       1
29                  1       3
30                  0       3
...               ...     ...
862                 0       2
863                 1       1
864                 0       3
865                 0       2
866                 1       2
867                 1       2
868                 0       1
869                 0       3
870                 1       3
871                 0       3
872                 1       1
873                 0       1
874                 0       3
875                 1       2
876                 1       3
877                 0       3
878                 0       3
879                 0       3
880                 1       1
881                 1       2
882                 0       3
883                 0       3
884                 0       2
885                 0       3
886                 0       3
887                 0       2
888                 1       1
889                 0       3
890                 1       1
891                 0       3

                                                          Name     Sex  Age  \
PassengerId
1                                      Braund, Mr. Owen Harris    male   22
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38
3                                       Heikkinen, Miss. Laina  female   26
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35
5                                     Allen, Mr. William Henry    male   35
6                                             Moran, Mr. James    male  NaN
7                                      McCarthy, Mr. Timothy J    male   54
8                               Palsson, Master. Gosta Leonard    male    2
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female   27
10                         Nasser, Mrs. Nicholas (Adele Achem)  female   14
11                             Sandstrom, Miss. Marguerite Rut  female    4
12                                    Bonnell, Miss. Elizabeth  female   58
13                              Saundercock, Mr. William Henry    male   20
14                                 Andersson, Mr. Anders Johan    male   39
15                        Vestrom, Miss. Hulda Amanda Adolfina  female   14
16                            Hewlett, Mrs. (Mary D Kingcome)   female   55
17                                        Rice, Master. Eugene    male    2
18                                Williams, Mr. Charles Eugene    male  NaN
19           Vander Planke, Mrs. Julius (Emelia Maria Vande...  female   31
20                                     Masselmani, Mrs. Fatima  female  NaN
21                                        Fynney, Mr. Joseph J    male   35
22                                       Beesley, Mr. Lawrence    male   34
23                                 McGowan, Miss. Anna "Annie"  female   15
24                                Sloper, Mr. William Thompson    male   28
25                               Palsson, Miss. Torborg Danira  female    8
26           Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female   38
27                                     Emir, Mr. Farred Chehab    male  NaN
28                              Fortune, Mr. Charles Alexander    male   19
29                               O'Dwyer, Miss. Ellen "Nellie"  female  NaN
30                                         Todoroff, Mr. Lalio    male  NaN
...                                                        ...     ...  ...
862                                Giles, Mr. Frederick Edward    male   21
863          Swift, Mrs. Frederick Joel (Margaret Welles Ba...  female   48
864                          Sage, Miss. Dorothy Edith "Dolly"  female  NaN
865                                     Gill, Mr. John William    male   24
866                                   Bystrom, Mrs. (Karolina)  female   42
867                               Duran y More, Miss. Asuncion  female   27
868                       Roebling, Mr. Washington Augustus II    male   31
869                                van Melkebeke, Mr. Philemon    male  NaN
870                            Johnson, Master. Harold Theodor    male    4
871                                          Balkic, Mr. Cerin    male   26
872           Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female   47
873                                   Carlsson, Mr. Frans Olof    male   33
874                                Vander Cruyssen, Mr. Victor    male   47
875                      Abelson, Mrs. Samuel (Hannah Wizosky)  female   28
876                           Najib, Miss. Adele Kiamie "Jane"  female   15
877                              Gustafsson, Mr. Alfred Ossian    male   20
878                                       Petroff, Mr. Nedelio    male   19
879                                         Laleff, Mr. Kristo    male  NaN
880              Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female   56
881               Shelley, Mrs. William (Imanita Parrish Hall)  female   25
882                                         Markun, Mr. Johann    male   33
883                               Dahlberg, Miss. Gerda Ulrika  female   22
884                              Banfield, Mr. Frederick James    male   28
885                                     Sutehall, Mr. Henry Jr    male   25
886                       Rice, Mrs. William (Margaret Norton)  female   39
887                                      Montvila, Rev. Juozas    male   27
888                               Graham, Miss. Margaret Edith  female   19
889                   Johnston, Miss. Catherine Helen "Carrie"  female  NaN
890                                      Behr, Mr. Karl Howell    male   26
891                                        Dooley, Mr. Patrick    male   32

             SibSp  Parch            Ticket      Fare        Cabin Embarked
PassengerId
1                1      0         A/5 21171    7.2500          NaN        S
2                1      0          PC 17599   71.2833          C85        C
3                0      0  STON/O2. 3101282    7.9250          NaN        S
4                1      0            113803   53.1000         C123        S
5                0      0            373450    8.0500          NaN        S
6                0      0            330877    8.4583          NaN        Q
7                0      0             17463   51.8625          E46        S
8                3      1            349909   21.0750          NaN        S
9                0      2            347742   11.1333          NaN        S
10               1      0            237736   30.0708          NaN        C
11               1      1           PP 9549   16.7000           G6        S
12               0      0            113783   26.5500         C103        S
13               0      0         A/5. 2151    8.0500          NaN        S
14               1      5            347082   31.2750          NaN        S
15               0      0            350406    7.8542          NaN        S
16               0      0            248706   16.0000          NaN        S
17               4      1            382652   29.1250          NaN        Q
18               0      0            244373   13.0000          NaN        S
19               1      0            345763   18.0000          NaN        S
20               0      0              2649    7.2250          NaN        C
21               0      0            239865   26.0000          NaN        S
22               0      0            248698   13.0000          D56        S
23               0      0            330923    8.0292          NaN        Q
24               0      0            113788   35.5000           A6        S
25               3      1            349909   21.0750          NaN        S
26               1      5            347077   31.3875          NaN        S
27               0      0              2631    7.2250          NaN        C
28               3      2             19950  263.0000  C23 C25 C27        S
29               0      0            330959    7.8792          NaN        Q
30               0      0            349216    7.8958          NaN        S
...            ...    ...               ...       ...          ...      ...
862              1      0             28134   11.5000          NaN        S
863              0      0             17466   25.9292          D17        S
864              8      2          CA. 2343   69.5500          NaN        S
865              0      0            233866   13.0000          NaN        S
866              0      0            236852   13.0000          NaN        S
867              1      0     SC/PARIS 2149   13.8583          NaN        C
868              0      0          PC 17590   50.4958          A24        S
869              0      0            345777    9.5000          NaN        S
870              1      1            347742   11.1333          NaN        S
871              0      0            349248    7.8958          NaN        S
872              1      1             11751   52.5542          D35        S
873              0      0               695    5.0000  B51 B53 B55        S
874              0      0            345765    9.0000          NaN        S
875              1      0         P/PP 3381   24.0000          NaN        C
876              0      0              2667    7.2250          NaN        C
877              0      0              7534    9.8458          NaN        S
878              0      0            349212    7.8958          NaN        S
879              0      0            349217    7.8958          NaN        S
880              0      1             11767   83.1583          C50        C
881              0      1            230433   26.0000          NaN        S
882              0      0            349257    7.8958          NaN        S
883              0      0              7552   10.5167          NaN        S
884              0      0  C.A./SOTON 34068   10.5000          NaN        S
885              0      0   SOTON/OQ 392076    7.0500          NaN        S
886              0      5            382652   29.1250          NaN        Q
887              0      0            211536   13.0000          NaN        S
888              0      0            112053   30.0000          B42        S
889              1      2        W./C. 6607   23.4500          NaN        S
890              0      0            111369   30.0000         C148        C
891              0      0            370376    7.7500          NaN        Q

[891 rows x 11 columns]

In [2]:
#Данные - таблица, двумерный массив
data[:10]
data["Age"][numpy.isnan(data["Age"])] = numpy.average(data.Age[numpy.logical_not(numpy.isnan(data["Age"]))])
print data

             Survived  Pclass  \
PassengerId
1                   0       3
2                   1       1
3                   1       3
4                   1       1
5                   0       3
6                   0       3
7                   0       1
8                   0       3
9                   1       3
10                  1       2
11                  1       3
12                  1       1
13                  0       3
14                  0       3
15                  0       3
16                  1       2
17                  0       3
18                  1       2
19                  0       3
20                  1       3
21                  0       2
22                  1       2
23                  1       3
24                  1       1
25                  0       3
26                  1       3
27                  0       3
28                  0       1
29                  1       3
30                  0       3
...               ...     ...
862                 0       2
863                 1       1
864                 0       3
865                 0       2
866                 1       2
867                 1       2
868                 0       1
869                 0       3
870                 1       3
871                 0       3
872                 1       1
873                 0       1
874                 0       3
875                 1       2
876                 1       3
877                 0       3
878                 0       3
879                 0       3
880                 1       1
881                 1       2
882                 0       3
883                 0       3
884                 0       2
885                 0       3
886                 0       3
887                 0       2
888                 1       1
889                 0       3
890                 1       1
891                 0       3

                                                          Name     Sex  \
PassengerId
1                                      Braund, Mr. Owen Harris    male
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female
3                                       Heikkinen, Miss. Laina  female
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
5                                     Allen, Mr. William Henry    male
6                                             Moran, Mr. James    male
7                                      McCarthy, Mr. Timothy J    male
8                               Palsson, Master. Gosta Leonard    male
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female
10                         Nasser, Mrs. Nicholas (Adele Achem)  female
11                             Sandstrom, Miss. Marguerite Rut  female
12                                    Bonnell, Miss. Elizabeth  female
13                              Saundercock, Mr. William Henry    male
14                                 Andersson, Mr. Anders Johan    male
15                        Vestrom, Miss. Hulda Amanda Adolfina  female
16                            Hewlett, Mrs. (Mary D Kingcome)   female
17                                        Rice, Master. Eugene    male
18                                Williams, Mr. Charles Eugene    male
19           Vander Planke, Mrs. Julius (Emelia Maria Vande...  female
20                                     Masselmani, Mrs. Fatima  female
21                                        Fynney, Mr. Joseph J    male
22                                       Beesley, Mr. Lawrence    male
23                                 McGowan, Miss. Anna "Annie"  female
24                                Sloper, Mr. William Thompson    male
25                               Palsson, Miss. Torborg Danira  female
26           Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female
27                                     Emir, Mr. Farred Chehab    male
28                              Fortune, Mr. Charles Alexander    male
29                               O'Dwyer, Miss. Ellen "Nellie"  female
30                                         Todoroff, Mr. Lalio    male
...                                                        ...     ...
862                                Giles, Mr. Frederick Edward    male
863          Swift, Mrs. Frederick Joel (Margaret Welles Ba...  female
864                          Sage, Miss. Dorothy Edith "Dolly"  female
865                                     Gill, Mr. John William    male
866                                   Bystrom, Mrs. (Karolina)  female
867                               Duran y More, Miss. Asuncion  female
868                       Roebling, Mr. Washington Augustus II    male
869                                van Melkebeke, Mr. Philemon    male
870                            Johnson, Master. Harold Theodor    male
871                                          Balkic, Mr. Cerin    male
872           Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female
873                                   Carlsson, Mr. Frans Olof    male
874                                Vander Cruyssen, Mr. Victor    male
875                      Abelson, Mrs. Samuel (Hannah Wizosky)  female
876                           Najib, Miss. Adele Kiamie "Jane"  female
877                              Gustafsson, Mr. Alfred Ossian    male
878                                       Petroff, Mr. Nedelio    male
879                                         Laleff, Mr. Kristo    male
880              Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female
881               Shelley, Mrs. William (Imanita Parrish Hall)  female
882                                         Markun, Mr. Johann    male
883                               Dahlberg, Miss. Gerda Ulrika  female
884                              Banfield, Mr. Frederick James    male
885                                     Sutehall, Mr. Henry Jr    male
886                       Rice, Mrs. William (Margaret Norton)  female
887                                      Montvila, Rev. Juozas    male
888                               Graham, Miss. Margaret Edith  female
889                   Johnston, Miss. Catherine Helen "Carrie"  female
890                                      Behr, Mr. Karl Howell    male
891                                        Dooley, Mr. Patrick    male

                   Age  SibSp  Parch            Ticket      Fare        Cabin  \
PassengerId
1            22.000000      1      0         A/5 21171    7.2500          NaN
2            38.000000      1      0          PC 17599   71.2833          C85
3            26.000000      0      0  STON/O2. 3101282    7.9250          NaN
4            35.000000      1      0            113803   53.1000         C123
5            35.000000      0      0            373450    8.0500          NaN
6            29.699118      0      0            330877    8.4583          NaN
7            54.000000      0      0             17463   51.8625          E46
8             2.000000      3      1            349909   21.0750          NaN
9            27.000000      0      2            347742   11.1333          NaN
10           14.000000      1      0            237736   30.0708          NaN
11            4.000000      1      1           PP 9549   16.7000           G6
12           58.000000      0      0            113783   26.5500         C103
13           20.000000      0      0         A/5. 2151    8.0500          NaN
14           39.000000      1      5            347082   31.2750          NaN
15           14.000000      0      0            350406    7.8542          NaN
16           55.000000      0      0            248706   16.0000          NaN
17            2.000000      4      1            382652   29.1250          NaN
18           29.699118      0      0            244373   13.0000          NaN
19           31.000000      1      0            345763   18.0000          NaN
20           29.699118      0      0              2649    7.2250          NaN
21           35.000000      0      0            239865   26.0000          NaN
22           34.000000      0      0            248698   13.0000          D56
23           15.000000      0      0            330923    8.0292          NaN
24           28.000000      0      0            113788   35.5000           A6
25            8.000000      3      1            349909   21.0750          NaN
26           38.000000      1      5            347077   31.3875          NaN
27           29.699118      0      0              2631    7.2250          NaN
28           19.000000      3      2             19950  263.0000  C23 C25 C27
29           29.699118      0      0            330959    7.8792          NaN
30           29.699118      0      0            349216    7.8958          NaN
...                ...    ...    ...               ...       ...          ...
862          21.000000      1      0             28134   11.5000          NaN
863          48.000000      0      0             17466   25.9292          D17
864          29.699118      8      2          CA. 2343   69.5500          NaN
865          24.000000      0      0            233866   13.0000          NaN
866          42.000000      0      0            236852   13.0000          NaN
867          27.000000      1      0     SC/PARIS 2149   13.8583          NaN
868          31.000000      0      0          PC 17590   50.4958          A24
869          29.699118      0      0            345777    9.5000          NaN
870           4.000000      1      1            347742   11.1333          NaN
871          26.000000      0      0            349248    7.8958          NaN
872          47.000000      1      1             11751   52.5542          D35
873          33.000000      0      0               695    5.0000  B51 B53 B55
874          47.000000      0      0            345765    9.0000          NaN
875          28.000000      1      0         P/PP 3381   24.0000          NaN
876          15.000000      0      0              2667    7.2250          NaN
877          20.000000      0      0              7534    9.8458          NaN
878          19.000000      0      0            349212    7.8958          NaN
879          29.699118      0      0            349217    7.8958          NaN
880          56.000000      0      1             11767   83.1583          C50
881          25.000000      0      1            230433   26.0000          NaN
882          33.000000      0      0            349257    7.8958          NaN
883          22.000000      0      0              7552   10.5167          NaN
884          28.000000      0      0  C.A./SOTON 34068   10.5000          NaN
885          25.000000      0      0   SOTON/OQ 392076    7.0500          NaN
886          39.000000      0      5            382652   29.1250          NaN
887          27.000000      0      0            211536   13.0000          NaN
888          19.000000      0      0            112053   30.0000          B42
889          29.699118      1      2        W./C. 6607   23.4500          NaN
890          26.000000      0      0            111369   30.0000         C148
891          32.000000      0      0            370376    7.7500          NaN

            Embarked
PassengerId
1                  S
2                  C
3                  S
4                  S
5                  S
6                  Q
7                  S
8                  S
9                  S
10                 C
11                 S
12                 S
13                 S
14                 S
15                 S
16                 S
17                 Q
18                 S
19                 S
20                 C
21                 S
22                 S
23                 Q
24                 S
25                 S
26                 S
27                 C
28                 S
29                 Q
30                 S
...              ...
862                S
863                S
864                S
865                S
866                S
867                C
868                S
869                S
870                S
871                S
872                S
873                S
874                S
875                C
876                C
877                S
878                S
879                S
880                C
881                S
882                S
883                S
884                S
885                S
886                Q
887                S
888                S
889                S
890                C
891                Q

[891 rows x 11 columns]

#Логистическая регрессия

In [3]:
def predict(W,X):
    """получить прогноз h(X|w)"""
    
    size = len(X) #размерность ответа
    X = numpy.array(X)
    pred = []
    for i in range(size):
        
        X_i = X[i,:]#i-тая строчка выборки примеров
        pred_i = sum(X_i*W) #прогноз модели для i-той строчки
        
        pred.append(pred_i) #предсказание модели для него
        
    a =  1/(1+numpy.e**(-1*numpy.array(pred)))
    return a

In [4]:
def loss(X,Y,W):
    "напиши функцию потерь, J(X,Y,W)"
    Y = numpy.array(Y).reshape(len(Y))
    pred = predict(W,X) #предсказание по модели
     
    margin = numpy.array([0]*len(pred))
    for i in range(len(pred)):
        margin[i] +=  -Y[i]*numpy.log(pred[i]) - (1-Y[i])*numpy.log(1-pred[i])

    return numpy.average(margin)

In [5]:
def gradient(X,Y,W):
    "посчитай вектор градиента функции потерь"
    len_gradient = len(W) #размер вектора градиента
    X = numpy.array(X)
    Y = numpy.array(Y).reshape(len(Y))

    #логарифм - numpy.log(m)

     
    grad = (predict(W, X)-Y)
    vecto = numpy.zeros(len_gradient)
    for i in range(len(Y)):
        vecto +=grad[i]*X[i]
    vecto/=len(Y)
    return vecto

In [6]:
def train_model(X,Y, step = 0.1,n_steps = 100):
    #создадим нулевой вектор весов
    len_w = X.shape[1] #сколько должно быть весов
    W = numpy.zeros(len_w)
    for i in range(n_steps):
        
        grad = gradient(X,Y,W) #вектор антиградиента
        
        W = W-grad*step #новый вектор весов
        
        
    return W

In [7]:
X = pandas.DataFrame()
X["age"] = data.Age
X["pclass"] = data.Pclass
X["fromS"] = data.Embarked=="S"
X["X0"] = 1

Y = pandas.DataFrame(data.Survived)

print X.shape, Y.shape

(891, 4) (891, 1)

In [8]:
from sklearn.cross_validation import train_test_split
X_train, X_test, Y_train,Y_test = train_test_split(X,Y,train_size = 0.6)

print X_train.shape, X_test.shape

(534, 4) (357, 4)

In [9]:
W = train_model(X,Y,step = 0.05, n_steps = 1000)

In [10]:
y_pred_train = predict(W,X_train)
y_pred_test = predict(W,X_test)

In [16]:
print "Ошибка на обучении:", loss(X_train,Y_train,W)
print "Ошибка на тесте:", loss(X_test,Y_test,W)

Ошибка на обучении: 1.08988764045
Ошибка на тесте: 1.00840336134

In [15]:
from sklearn.metrics import roc_auc_score
print "AUC на обучении:", roc_auc_score(Y_train,y_pred_train)
print "AUC на тесте:", roc_auc_score(Y_test,y_pred_test)

AUC на обучении: 0.885016800434
AUC на тесте: 0.860156724988